# Generated by Django 4.2.6 on 2023-10-29 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='payed_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Dibayar Pada'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='unix_date_for_month',
            field=models.IntegerField(unique=True),
        ),
    ]
