# Generated by Django 4.2.6 on 2023-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_payment_date_time_payment_payed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dibayar Pada'),
        ),
    ]
