# Generated by Django 4.2.6 on 2023-10-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payment_payed_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Tagihan', 'verbose_name_plural': 'Tagihan'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pembayaran', 'verbose_name_plural': 'Pembayaran'},
        ),
    ]
