# Generated by Django 4.2.6 on 2023-10-29 13:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bill_options_alter_payment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.DateTimeField(default=core.models._get_default_expired)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payment')),
            ],
        ),
    ]
