# Generated by Django 4.2.6 on 2023-10-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymentproccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproccess',
            name='unique_code',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
